### PR TITLE
Unify downloaded folder handling for cewe_folder.txt and cewe2pdf.ini

### PR DESCRIPTION
**Pull request by cweiske**
Downloaded cliparts, fonts and masks were only used when cewe_folder.txt
exists. Also, this only worked on Linux and MacOSX.

This patch unifies the loading of downloaded data, so that cewe_folder.txt
and cewe2pdf.ini configuration are on par.
Downloaded data are now only loaded from the correct "key account" number
directory inside the hps folder, and not from all of the folders.

Support for Windows is also added (loading data from "${PROGRAMDATA}/hps/"
instead of only "~/.mcf/hps/").

This has not actually been tested on Windows.
Please try and report if it works!

Followup to https://github.com/bash0/cewe2pdf/pull/79

@AnEnglishmanInNorway please test on windows if you use Windows.

### CODE REVIEW

**Comment by AnEnglishmanInNorway** [comment]
I don't have my machine with me at present but will try to check this out
on Windows when I get back.

**Review by AnEnglishmanInNorway — APPROVED** [review]
This works fine on Windows. In fact, as I suspected it would, these changes make it unnecessary to use the _extraBackgroundFolders_, _extraClipArts_ and _passepartoutFolders_ entries in the .ini file. A dramatically better solution, I'm impressed.

**Comment by cweiske** [comment]
@AnEnglishmanInNorway Should we drop support for the extraBackgroundFolders, extraClipArts and passepartoutFolders ini entries?

**Comment by AnEnglishmanInNorway** [comment]
Probably. But hang on a while, we can maybe drop the font family definition as well, making the .ini file redundant ... except that it may be handy to have in the future. I introduced it because the simple cewe_folder.txt was not extensible if we wanted to add preferences which were not sensible on the command line.

**Comment by cweiske** [comment]
dpi and background dpi should be configurable on cli or ini file.

Line height is the last big problem I see. But that does not need a config option, but a new way of calculation.

**Comment by AnEnglishmanInNorway** [comment]
I devoted some time to improving the text handling a while back, and line height is certainly tricky. Page 6 of the unittest fotobook contains several examples of lines with differing text sizes and heights. A long piece of text with no line breaks but with varying text sizes will of course contain lines of different heights because of the text variation; then on top of that there is the leading between the lines, determined by a constant scale factor applied the largest font size used in a piece of text. Based on experimentation I determined that 1.1 was a sensible scaling - the result, for me, looks OK.
I'd be interested to know what it is that you do with your texts that causes them to need specific attention. One thing that I can imagine might cause trouble would be a small section of large size text in a long piece of text, because the leading is based on applying the scale factor to the largest point size noted in the entire text - you could end up with much wider spacing than planned. I didn't see how to avoid that within the capability of the reportlabs package. Is it possible to see the XML of the texts that have caused you trouble? And maybe you can remember how you created them in the photo editor? We could add them as examples in the unittest book.
Another thought. You say you used line heights of 1.5, 1.2, and 1.1. I assume that means that you changed the line_scale in the code to those values?

**Pull request merged**
