### PR TITLE
Add page numbers cli option

### PR DESCRIPTION
**Pull request by cweiske**
Resolves: https://github.com/bash0/cewe2pdf/issues/83

### CODE REVIEW

**Review by AnEnglishmanInNorway — CHANGES_REQUESTED** [review]
Christian looks to be a more experienced GitHub user than me, so I suspect that I (we?) will learn a little about process here.
Using PR 86 as a simple start to trying his mods I used Visual Studio to create myself a branch containing the changes and tried recreating the unittest fotobook, starting the test_simpleBook.py file with the tests\unittest_fotobook.mcf file as an argument.
Exception on line 24, Message=convertMcf() missing 1 required positional argument: 'pageNumbers'
So ... all the other uses of convertMcf need to be updated with a pageNumbers argument, probably None is the best. There are four:
cewe2pdf\processManyMcfs.py(14):convertMcf(filename, False) # throwing away the result
cewe2pdf\tests\testClipart\test_drawClipart.py(28):convertMcf(inFile, keepDoublePages)
cewe2pdf\tests\testFontDoesNotExist\test_fontDoesNotExist.py(29):convertMcf(inFile, keepDoublePages)
cewe2pdf\tests\test_simpleBook.py(24):convertMcf(inFile, keepDoublePages)
That gave me the opportunity to use the GitHub review window in VS2019, and submit this review.
Now what happens?

**Comment by cweiske** [comment]
I've set a default value for the pages argument of convertMfc(). This is more sane than modifying each call's parameters.

**Comment by AnEnglishmanInNorway** [comment]
Assuming that I have got all your changes (a brave assumption, my git background is still limited) then I don't see what you have done. I see that the `parser.add_argument` call sets a default of none, but that doesn't solve the problem because the other calls to ConvertMcf are from other python files (in particular tests/test_simpleBook.py) which do not use that argument parsing.
I would have thought that the best backward compatible change would have been to set a default value in the definition of ConvertMcf itself:
`def convertMcf(mcfname, keepDoublePages: bool, pageNumbers = None):`
With that change, all the existing calls to convertMcf will do exactly what they did before, while the main program will have the benefit of the --pages spec.
Or did I misunderstand something?

**Comment by cweiske** [comment]
Something went wrong here.

**Comment by cweiske** [comment]
I've changed the parameter to `, pageNumbers = None`, as I thought I had done it before. Apparently I didn't, but I am sure that I already did :(

**Comment by AnEnglishmanInNorway** [comment]
Thank you! That makes me feel a lot better - I thought I must have done something wrong in the pull/push/fetch/merge. Now to see if I can figure out how to bring in the rest of your work and have a look.

**Comment by cweiske** [comment]
Your commit "Adds default None to ConvertMcf pagenumbers" should not be necessary because I already fixed it in https://github.com/bash0/cewe2pdf/commit/3ceaec3a52c23c04284812476d3e3e3c5285197c
(a force-push)

You'd need to hard reset your local branch to mine. (git checkout pagenumbers && git reset --hard cweiske/pagenumbers)

**Comment by AnEnglishmanInNorway** [comment]
Ouch. As I said, despite a lifetime of using various version control systems, I am definitely a novice here. I fear I just committed to your branch, which was not my intention. The change was only what we agreed on, plus a .gitignore change to ignore a couple of my local files. My apologies.

**Comment by AnEnglishmanInNorway** [comment]
Thanks for the feedback. Getting used to the terminology and workflows is taking a while. Doing a "hard reset" feels a bit heavy! I'm actually using a combination of the GitHub desktop application and the Visual Studio GitHub integration, which of course has the advantage of hiding the nitty gritty details and the disadvantage of hiding the understanding of those details. What I wanted to do was to merge your all changes to a branch of my own master, and then finally merge the result back on to bash0/master (I suspect that @bash0 doesn't have time to follow cewe2pdf very much, so I asked for permission to do that - I'm retired so I at least I don't have a job making demands on my time:-)

**Comment by cweiske** [comment]
Wrapping the head around [rebases](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) takes some time, but it's actually pretty easy. It prevents those pesky merge commits and leads to a clean git history.
Hard resets are necessary if someone modified commits (instead of creating an additional fix commit) in his branch, and you want to get the new state.

I've rebased all my other patches against the current master, so they can be merged cleanly.

**Comment by AnEnglishmanInNorway** [comment]
I'll get there in the end. I observe that the merge option for a pull
request (in the GitHub web interface) has three choices, shown in the
picture
[image: image.png]
Given your comment about "pesky merge commits" and this article
<https://devblogs.microsoft.com/devops/squash-a-whole-new-way-to-merge-pull-requests/>
which I found when looking for an explanation of squashing, I assume
you would recommend that I choose "squash and merge" to bring your stuff
into the master?

**Comment by cweiske** [comment]
Hi pete,

squashes are only necessary if there are "fix up" commits that fix problems with a previous commit.
I personally do not do this, but amend my commits so that they are perfect. If my pull requests have multiple commits, then only because they make sense.

Please use the "rebase and merge" option, not squash+merge.
-- 
Regards/Mit freundlichen Grüßen
Christian Weiske

**Pull request merged**
