### PR TITLE
Replace tab by nbsp and cleaning whitespaces

### PR DESCRIPTION
**Pull request by chharms**

### CODE REVIEW

**Comment by chharms** [comment]
Clean-up some more spaces

**Comment by chharms** [comment]
Are pull requests automatically taking latest version or are they fixed to the version when the request was generated?

**Comment by AnEnglishmanInNorway** [comment]
It seems to me they are taking the latest version which is synced. 
Which brings me to a question about the changes here. I guess we are using different development environments because I see that the vast majority of the lines that have changed in this update are spacing changes. I use Visual Studio Community Edition and basically let it organise leading spaces/tabs on the basis of options (which I have not changed from the default). I can easily set something else if I'm doing something unusual.
We probably have different programming backgrounds as well - I've been a C/C++/C# user for a lifetime, and that surely affects the way I code and use spacing. I have never used Python before so this has been an interesting experiment. I can't say I like a language where indentation is syntactically significant!
Finally, on the issue of the tabs, I had a quick look at the old code, which I think is making an assumption about the average width of a character, counting the characters it has output to a line, and then moving accordingly. I can't see that working very well with a variable width font, but ... perhaps we could implement something similar for use with a fixed width font such as Courier or Lucida Console, on the assumption that the user has made his text area so wide that the text will never wrap between paras or linebreaks. Space should be fixed width in these fonts as well, though we might have to use an nbsp or one of the more specialized spaces.

**Comment by chharms** [comment]
My background is on Pascal, C, C++, Perl and nowadays Python. The "indentation logic" is unusual, I agree. The interpreter checks for indentation and refuses a mixture of tab and spaces; currently this code uses 4 spaces for a level and cries when indentation is not a multiple of 4. 
I had a look into the rebuild test result and found a high number of warnings. I focused on spacing and the like in the main file, but there are still others left (e.g. "line too long, "do not use bare 'except'" or "comparison to None should be 'if cond is None:'"). The overall test result is still failed because page count does not match expectation.

**Comment by AnEnglishmanInNorway** [comment]
I found some "edge" cases which your latest merge wouldn't handle, and hope I have fixed them in https://github.com/bash0/cewe2pdf/pull/42 without breaking your results. The br tags really are a bit nasty! I've attached a picture of an example which you might not have seen, with br inside a span with tail text. Also pictures of the existing test text page and my new test text page in the unit test. Looks fair:-)

brsinspans
unittestincewe
unittestinpdf

**Comment by chharms** [comment]
It seems in S-Enter, the br (inside span) are swallowed now and from somewhere comes an unmotivated &nbsp plus a blank before 2nd "Blue".
I did not observe those in my PDF.

**Comment by AnEnglishmanInNorway** [comment]
Yepp, I'm really sorry. I have to stop now but I have checked in something that looks like this. I've added nbsp in a couple of places because the pdf generation seems to swallow blank lines. We have guests over the weekend so I fear I will not be able to look much more until monday.
unittestinpdf

**Comment by chharms** [comment]
One question to the code snippet from MCF above: Is it generated by CEWE software or manually edited?

**Comment by chharms** [comment]
Compared to what we had last week: Awesome!

**Comment by AnEnglishmanInNorway** [comment]
The HTML, you mean? I opened the mcf file as XML in Visual Studio, searched for the bit that was giving me trouble, copied the contents of the CDATA section into Notepad++ with the XML tools plugin loaded, and asked for it to be pretty printed. I don't think I could work with XML/HTML without being able to see it structured properly!

**Comment by AnEnglishmanInNorway** [comment]
Ah. I just understood what you really asked. I haven't generated any of my
examples by hand. Everything with the editor. I think a lot depends on
exactly where you have the cursor (or selection) when you make some change.

**Pull request merged**
