### PR TITLE
Fix issue 114

### PR DESCRIPTION
**Pull request by AnEnglishmanInNorway**
Fix issue https://github.com/bash0/cewe2pdf/issues/114

### CODE REVIEW

**Comment by chharms** [comment]
I assumed this project is dead after CeWe switched to the All-in-One mcfx format. But no, it's still alive and I figured out you can still "Save as" in the old, well established mcf format.

But I found another issue with the new software: Background location has changed and appears in e.g.:
`C:\Programme\CEWE\RINGFOTO FOTOWELT\Resources\photofun\backgrounds\201/201/201.jpg` OR
`c:/Users/xxx/AppData/Local/Anwendungsdaten/CEWE/hps/15079/photofun/backgrounds\6870/6870/6870.jpg`

We can specify the aditional location in `extraBackgroundFolders`, but we also got two additional folder level with the name of the background. I simply made it working by passing `bg+'/'+bg+'/'+bg + '.bmp'` and so on, and will think about a proper solution.

**Comment by AnEnglishmanInNorway** [comment]
I had noticed the same change, and made a simple fix (changeset [09ea02e](https://github.com/bash0/cewe2pdf/pull/115/commits/09ea02eef8181f45a65984244a6f993238badb48)) to look for the top level hps folder first in the personal data location, and then failing that in the (old version) common data location. I had assumed that they were exclusive rather than additive. Since my albums worked OK, I assumed that the latest version (07.02.05 from my cewe franchiser) had moved all the stuff to the new location, rather than using both.
The mcfx format hasn't arrived here yet. That's a bit irritating. Do we have any idea what they have done? mcf to mcfx sounds a bit like Microsoft going from their proprietary doc to docx, but that was a real change. mcf is already xml, so it almost sounds as though they might just have rearranged the schema. I assume the new version offers an upgrade path in the fotobook program from mcf to mcfx, which ought to allow us to compare the two formats and see how much they have changed

**Comment by AnEnglishmanInNorway** [comment]
Once again I fear I have been less than well organised. I've just "rebase and merged" my recent minor changes

- preliminary(?) adaptation to cewe having moved the hps folder
- an exception in an exception handler as revealed by the abovementioned move of the hps folder 
- bringing in seaeagle1's fix for transparent text backgrounds

Sorry the confusion, but I hope the result in the base is ok.

**Comment by chharms** [comment]
The current unittest_fotobook.mcf says `createdWithHPSVersion="7.0.1"` whereas my files are created containing `createdWithHPSVersion="7.3.1"`.
I tried to open and convert it to new format. but I struggle with font "ARLRDBD.TTF" (aka "Arial Rounded MT Bold"). It's not part of my installed standard fonts. Is it commonly installed elsewhere?

**Comment by AnEnglishmanInNorway** [comment]
This is surely for some of the text tests that I have added, since I use
that font in my own albums. A quick google search for arlrdbd.ttf hits lots
of places where you could get the file (which unsurprisingly originally
comes from Microsoft Office) though I imagine many of those places may be
dubious. Microsoft describes the font here:
https://learn.microsoft.com/en-us/typography/font-list/arial-rounded-mt.
The font faq referred there prohibits redistribution so this is clearly a
bit tricky for those of us who don't use Office - not that it seems to have
stopped people sharing the file. There's even a copy in a project on
github,
https://github.com/jathusanT/pebble_pedometer/blob/master/resources/fonts/ARLRDBD.TTF
.
I guess that puts the ball in my court to locate and change the texts to
some more openly available font while maintaining the usefulness of the
tests I have added, though I can't promise immediate action, I'm afraid.
Any suggestion as to a good open source font to choose which will be OK for
both vanilla Windows and Linux?

**Comment by chharms** [comment]
Maybe you can find a similar font in Resources\photofun\fonts, that would be available independent of underlying OS, I assume.

**Comment by AnEnglishmanInNorway** [comment]
Of course. I had a quick look, perhaps I can use Nunito. That has the
advantage of being open font licensed:
https://fonts.google.com/specimen/Nunito/about. I assume that means that we
could check in the ttf in the project test resources for use in the
checkin build (where cewe fonts are not available)

**Comment by chharms** [comment]
Yes, Nunito-Bold.ttf looks not so much different. I just tried it by replacing the string in mcf file, line gap is increased and character width seems to be smaller. Thus, formatting is messed up a bit.

**Comment by AnEnglishmanInNorway** [comment]
I'll see what I can do. I don't recall exactly what I was testing, other
than that it was possible to mix and match various text variations (size,
colour, font, etc), including the use of new line vs new paragraph. I
certainly have no automated check that the result is "correct" in a formal
sense, it's a visual inspection - I have old versions of the resulting pdf
locally here, and I just eyeball against the most recent. My last local
copy is attached. Perhaps I should check them in.

**Comment by AnEnglishmanInNorway** [comment]
My final message until Christmas and probably New Year are over. I did a global replacement of "Arial Rounded MT Bold" with "Arimo" in the mcf file (29 instances), and made no other changes at all. Reran cewe2pdf, the resulting pdf looks good on my rapid visual inspection versus the previous version. The typeface is not as heavy, of course, but I don't think that is the point here - the texts are demonstrating other capabilities than the actual design of the font. Arimo is delivered with cewe and is Apache 2.0 license (https://fonts.google.com/specimen/Arimo?query=arimo) so we should be ok on that. So Arimo is my choice.

**Comment by chharms** [comment]
`   *`
`  / \`
` /   \`
`   ^`

**Pull request merged**
