### PR TITLE
 Add some more text blocks to unittest_fotobook

### PR DESCRIPTION
**Pull request by chharms**
I appreciate the idea of using reportlab, that's really is an improvement.
But some formatting stuff got broken now, the updated unittest_fotobook contains some new text blocks pointing out the weaknesses:
- tabs spacing got lost
- <Shift-Enter> behaves different from <Enter>
- format changes end up in linefeeds
- after using a different colour than black, switching to black is ignored

### CODE REVIEW

**Comment by AnEnglishmanInNorway** [comment]
Still struggling to coordinate merges and pushes and pulls and so on, but I have your changes. My version of the cewe executable is clearly older than yours, but it seems to load anyway despite the warning message. Nice set of tests on page 4 :-)  I'll have a quick look, but I have a nasty suspicion that since it is now reportlabs that is formatting the text, at least the tabs may be an issue in that code rather than ours. Shift-Enter and Enter may be us though - until my very last change which you may not have, the shift-enter case was definitely bad.

**Comment by chharms** [comment]
I found another issue:
Sometimes font-size is a float like 8.5 e.g.
Can be fixed by replacing int(...) by floor(float(...))
BTW: once there is strip("pt"), once strip()[:-2]. I would prefer the first.

Other poin regarding black color:
When color is black, it's not always explicitly set. Thus `if 'color' in style:` needs an else to set `color = "#000000"`

**Comment by AnEnglishmanInNorway** [comment]
OK, this is going to be a bit more complex than BarchSteel's first approach - which I have to say worked absolutely perfectly for my 10 albums, where my texting is clearly a lot simpler than it could have been!  We need to agree on a strategy, I suspect. I think we may have to change to using one reportlab Paragraph per HTML p tag we find in the mcf file. We'll have to build up all the text, adding the texts from the span tags as we come across them, and then create the Paragraph and put it into the flow.
Looking at the paragraph.py file I see from the fairly extensive comments on the class (around line 1475) that

        The paragraph Text can contain XML-like markup including the tags:
        <b> ... </b> - bold
		...
In fact one of the XML-like tags is span, but their syntax is different from the XML syntax. We can probably translate from one to the other, at least for simple things like size, font and colour.
What I do not see is that they implement the line break tag, br. I think we'll just have to experiment with that.

**Comment by chharms** [comment]
Yep. Either the entire `<p> ... </p>` can go into one paragraph, or it has to be split at the line breaks. But not for each span separately.
I could remove `<para> </para>` (just using `text`) without any visible effect. Mhm. Have to think about it.

**Comment by AnEnglishmanInNorway** [comment]
I don't think removing the para will make any difference, it seems to be just a way of setting paragraph level attributes. I'm moving on the idea of building up a string containing the XML-like span tags. It looks vaguely promising **but** it seems that the Paragraph class is not very good at setting the line height as the font size changes between spans. The lines all end up at the same size and therefore crash into one another. Will work a bit more on it, but I'm soon going to have to start on building a wall in the garden ...

**Comment by chharms** [comment]
The best might be to convince Paragraph not to insert linefeeds, and we add them on `<br>` and  `</p>` manually.

**Comment by AnEnglishmanInNorway** [comment]
I'm not sure Paragraph is going to cooperate on that. My current effort looks like the attached file, which is improved with respect to the new lines on style changes, and I think might get there in the end. But I think it might be worth worrying about tabs before completing this, because it could well be that Paragraph just doesn't do tabs. Perhaps we should consider prescanning the textarea for the presence of "difficult" stuff, such as tabs, and in that case process the area with the old code instead of the new Paragraph based stuff. A bit of a hack but it would make simple texts work well, while letting complexly structured texts be processed as they were before.
[unittest_fotobook.mcf.pdf](https://github.com/bash0/cewe2pdf/files/4554159/unittest_fotobook.mcf.pdf)

**Comment by AnEnglishmanInNorway** [comment]
Mmm. 9 years ago they said they didn't do tabs in paragraphs https://reportlab-users.reportlab.narkive.com/ycL66gcP/insert-tab-in-reportlab-platypus-paragraph
I've found one or two other places which suggest that tabs are not implemented in paragraph, so the idea of splitting to "layout texts" (old code) and "prose texts" (new code) is beginning to look attractive. But I think the new code should still be updated along the lines of my work to accept colour and size changes in the prose text.

**Comment by AnEnglishmanInNorway** [comment]
Could somebody let me have an additional_fonts.txt file for the unit test?

**Comment by chharms** [comment]
Much better, the lines are almost as they should be. Astonishing is the big difference it makes between w.r.t. line breaks.

**Comment by chharms** [comment]
Bodoni = C:\Program Files\CEWE\RINGFOTO FOTOWELT\Resources\photofun\fonts\Bodoni-Regular.ttf
Stafford = C:\\Program Files\\CEWE\\RINGFOTO FOTOWELT\\Resources\\photofun\\fonts\\Stafford-Light.ttf
CalligraphScript = C:\Program Files\CEWE\RINGFOTO FOTOWELT\Resources\photofun\fonts\CalligraphScriptCEWE-Regular.ttf
FranklinGothic = C:\Program Files\CEWE\RINGFOTO FOTOWELT\Resources\photofun\fonts\FranklinGothic-Medium.ttf
Calibri = C:\Windows\Fonts\calibri.ttf

**Comment by AnEnglishmanInNorway** [comment]
A quick status, so nobody else wastes time duplicating my work. Page 4 of the unit test has improved with respect to line breaks and sizes when using shift-enter. I have yet to look at the enter block. I have to say that Cewe generates some interesting html, and that the python parser does not do a good job on it - in fact, there is one br tag that I believe it does not give me. This is a really well designed test!
Annotation 2020-04-30 003923

**Comment by AnEnglishmanInNorway** [comment]
Take a look at pull request https://github.com/bash0/cewe2pdf/pull/34. As my remarks say, it is definitely not good yet, but it is definitely better and I don't think it has broken anything for "simpler" text areas. If I don't find time to improve this myself, at least it gives somebody else a start point.
Capture

**Pull request merged**
