### PR TITLE
Fix .mcfx data.mcf timestamp handling, add clipart flipping

### PR DESCRIPTION
**Pull request by cweiske**
The actual new feature here is horizontal and vertical clipart flipping.

2024-05-07 clipart flipping

### CODE REVIEW

**Comment by cweiske** [comment]
Wait. Something is wrong here.
My test mcfx works, the real production mcfx not :(

**Comment by AnEnglishmanInNorway** [comment]
I'm so happy that also other people think stuff is "ready to go" and then suddenly discover that it wasn't after all. I keep doing that! A question ... a couple of times now you have tidied up trailing spaces in a file which I have created (I use Visual Studio 2022 Community Edition). I'm not sure what causes that but I'll see if I can find an option to avoid it. Is it just a standard that you like to use, or does it cause trouble in your environment?

**Comment by cweiske** [comment]
> I'm so happy that also other people think stuff is "ready to go" and then suddenly discover that it wasn't after all. I keep doing that!

:) I suspect that the clipart in the production file is an image and not a clipart, and now I have to implement flipping support for images, too.

> a couple of times now you have tidied up trailing spaces in a file which I have created (I use Visual Studio 2022 Community Edition). I'm not sure what causes that but I'll see if I can find an option to avoid it. Is it just a standard that you like to use, or does it cause trouble in your environment?

I use emacs as editor on all my machines and configure it to automatically trim trailing whitespace upon saving.
This - and other things I enforce in my own projects like a strict coding style - have one single goal: Keeping diffs in commits minimal, which makes reviews easier and make it easier to understand commits when looking at them later.
Stray space characters at the end of lines pollute those diffs and make them harder to read.

**Comment by AnEnglishmanInNorway** [comment]
Perhaps we should bring in your work so far, and then you can decide what to do about images as a separate effort?

I agree with your adherence to a strict formatting standard, and indeed was once responsible for programmatically enforcing it on checkin (to SCCS on Unix V7, so that tells you how long I've been programming:-) I've learnt Python on my own late in life as a result of this project and don't suppose I'll get as far as a "standard" style, but - as you'll have seen - I've now introduced trailing space removal on save. I have a VS extension called Codemaid for C#, C++, etc code tidying, but it doesn't do Python. Perhaps there is a similar extension for Python, but that might open a whole Pandora's box about what standard to adopt!!

**Comment by cweiske** [comment]
It turned out that the `zposition` value I use in the first patch version has nothing to do with flipping at all :)
Cliparts have a `mirror` attribute in their `ClipartConfiguration` that I completely ignored, and which was the reason it did not work in the production mcfx file.

With the new patch flipping works, also flipping + rotating (first hedgehog):
2024-05-08 cewe2pdf flip+rotate pdf

**Comment by AnEnglishmanInNorway** [comment]
Nice. Perhaps you could let me have the mcf file containing references to the clips and images you have used here? I have begun to add some data for each (visible) issue to the checked-in _unittest_fotobook.mcf_ so that I can at least eyeball for changes between an old version and a new version of _unittest_fotobook.mcf.pdf_ 

Alternatively, there is a _cewe2pdf\tests\testCliparttestClipart.mcf_ which we could update. That's a bit more work because it runs as part of the github build action on bash0/cewe2pdf, and needs to have copies of the cliparts it uses checked in to _cewe2pdf\tests\Resources\photofun\decorations_

**Pull request merged**
